# ============================================
# ANSIBLE INVENTORY ФАЙЛ
# ============================================

# --------------------------------------------
# ГРУППА: Веб-серверы 
# --------------------------------------------
[webservers]
web-1 ansible_host=89.169.150.141 fqdn=fhmsluvvtemhja6igvpo.auto.internalweb-2 ansible_host=89.169.136.80 fqdn=fhmu3dmh86slgsuajbss.auto.internal
# --------------------------------------------
# ГРУППА: Базы данных
# --------------------------------------------
[databases]
db-main ansible_host=84.201.173.39 fqdn=fhmve6ivrou0hk9g8hb1.auto.internaldb-replica ansible_host=89.169.150.248 fqdn=fhm3hg8k98abpmkfett1.auto.internal
# --------------------------------------------
# ГРУППА: Storage
# --------------------------------------------
[storage]
storage ansible_host=89.169.130.224 fqdn=fhm4g14vcsfde9clmn3a.auto.internal
# --------------------------------------------
# ОБЩИЕ ПЕРЕМЕННЫЕ ДЛЯ ВСЕХ ХОСТОВ
# --------------------------------------------
[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
host_key_checking=False
