# ============================================
# ANSIBLE INVENTORY ФАЙЛ
# ============================================

[webservers]
web-1 ansible_host=10.0.1.12 fqdn=fhm4e28js780kuq9pdpg.auto.internal
web-2 ansible_host=10.0.1.16 fqdn=fhm7pm6joiu5tt7tefh0.auto.internal

[databases]
db-main ansible_host=10.0.1.27 fqdn=fhm5mrv63hiricfcsg6l.auto.internal
db-replica ansible_host=10.0.1.7 fqdn=fhmhteaafh0l3i5oofoo.auto.internal

[storage]
storage ansible_host=10.0.1.23 fqdn=fhm8igv2fljg204krj94.auto.internal

[bastion]
bastion ansible_host=51.250.71.247 fqdn=fhmr9q7uus8rc1hmngfu.auto.internal

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
host_key_checking=False
ansible_python_interpreter=/usr/bin/python3

# Proxy через bastion (если есть)

[webservers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@51.250.71.247"'

[databases:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@51.250.71.247"'

[storage:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@51.250.71.247"'
